[0m12:07:00.749590 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000028B8690B6E0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000028B83469FA0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000028B8690A600>]}


============================== 12:07:00.758111 | d31781f0-7b42-448b-a30b-2fcbdf3a3225 ==============================
[0m12:07:00.758111 [info ] [MainThread]: Running with dbt=1.9.4
[0m12:07:00.759111 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'debug': 'False', 'profiles_dir': 'C:\\Users\\Lo√Øse\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'invocation_command': 'dbt run', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m12:07:00.760108 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\Lo√Øse\Documents\SupInfo\10-4DATA\4data_projet\project_dagster\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m12:07:00.761106 [debug] [MainThread]: Command `dbt run` failed at 12:07:00.760108 after 0.17 seconds
[0m12:07:00.761106 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000028B86C510A0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000028B86C53080>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000028B86D94DA0>]}
[0m12:07:00.761106 [debug] [MainThread]: Flushing usage events
[0m12:07:01.217421 [debug] [MainThread]: An error was encountered while trying to flush usage events
